[package]
name = "carcassonne"
version = "0.1.0"
authors = ["Tim Brenner <timpbrenner@gmail.com>"]

[dependencies]
actix-web = "0.6.10"
diesel = { version = "1.3.0", features = ["postgres"] }
dotenv = "0.9.0"
env_logger = "0.5.10"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
